ecommerce/app/urls.py
from .forms import LoginForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.urls import include, path
from . import views
from django.contrib.auth import views as auth_views
from .views import error_400_view
from rest_framework import routers
from .views import ProductViewSet

router = routers.DefaultRouter()
router.register(r'product', ProductViewSet)


app_name = 'app'


urlpatterns = [
    path('', views.home, name="home"),
       
    path('add-to-cart/', views.add_to_cart, name="add-to-cart"),
    path('remove-cart/<int:cart_id>/', views.remove_cart, name="remove-cart"),
    path('plus-cart/<int:cart_id>/', views.plus_cart, name="plus-cart"),
    path('minus-cart/<int:cart_id>/', views.minus_cart, name="minus-cart"),
    path('cart/', views.cart, name="cart"),
    path('checkout/', views.checkout, name="checkout"),
    path('orders/', views.orders, name="orders"),
    #URL for Products
    path('product/<slug:slug>/', views.detail, name="product-detail"),
    path('categories/', views.all_categories, name="all-categories"),
    path('shop/', views.shop, name="shop"),
    # URL for Authentication
    path('app/register/', views.RegistrationView.as_view(), name="register"),
    path('login/', auth_views.LoginView.as_view(template_name='app/login.html', authentication_form=LoginForm), name="login"),
    path('app/profile/', views.profile, name="profile"),
    path('app/add-address/', views.AddressView.as_view(), name="add-address"),
    path('app/remove-address/<int:id>/', views.remove_address, name="remove-address"),
    path('app/logout/', auth_views.LogoutView.as_view(next_page='app:login'), name="logout"),

    path('app/password-change/', auth_views.PasswordChangeView.as_view(template_name='app/password_change.html', form_class=PasswordChangeForm, success_url='/app/password-change-done/'), name="password-change"),
    path('password-change-done/', auth_views.PasswordChangeDoneView.as_view(template_name='app/password_change_done.html'), name="password-change-done"),

    path('app/password-reset/', auth_views.PasswordResetView.as_view(template_name='app/password_reset.html', form_class=PasswordResetForm, success_url='/app/password-reset/done/'), name="password-reset"), # Passing Success URL to Override default URL, also created password_reset_email.html due to error from our app_name in URL
    path('app/password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='app/password_reset_done.html'), name="password_reset_done"),
    path('app/password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='app/password_reset_confirm.html', form_class=SetPasswordForm, success_url='/app/password-reset-complete/'), name="password_reset_confirm"), # Passing Success URL to Override default URL
    path('app/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='app/password_reset_complete.html'), name="password_reset_complete"),

    path('product/test/', views.test, name="test"),
    path('add-to-wishlist/<int:prod_id>/', views.add_to_wishlist, name='add-to-wishlist'),
    path('shop/<slug:gender_slug>/category/<slug:category_slug>/', views.filter_by_gender_category, name='filter-by-gender-category'),
    path('blog/', views.blog, name='blog'),
    path('blog/<slug:slug>/', views.blog_detail, name='blog-detail'),
    path('contact', views.contact, name='contact'),
    path('wishlist/', views.wishlist, name='wishlist'),


    path('<slug:slug>/', views.category_products, name="category-products"),
    
    # path('<path:not_found>', error_400_view, name='catch_all_404'),

    
] 
# handler401 = error_400_view

ecommerce/app2/urls.py
from django.urls import path
from . import views
from django.urls import re_path
from django.contrib.auth import views as auth_views
from .views import error_400_view


app_name = 'app2'

urlpatterns = [
    path('home', views.DashboardView.as_view(), name='home'),
    path('login/', views.App2LoginView.as_view(), name='app2login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='app2:app2login'), name="app2logout"),
    path('products/', views.ProductListView.as_view(), name='product_list'),
    path('products/add_edit/', views.ProductAddEditView.as_view(), name='add_edit_product'),
    path('products/add_edit/<slug:product_slug>/', views.ProductAddEditView.as_view(), name='add_edit_product'),
    path('products/delete/<slug:product_slug>/', views.ProductDeleteView.as_view(), name='delete_product'),
    path('blog_post/', views.BlogPostListView.as_view(), name='blog_post_list'),
    path('blog_post/add_edit/', views.BlogPostAddEditView.as_view(), name='add_edit_blog_post'),
    path('blog_post/add_edit/<slug:blog_post_slug>/', views.BlogPostAddEditView.as_view(), name='add_edit_blog_post'),
    path('blog_post/delete/<slug:blog_post_slug>/', views.BlogPostDeleteView.as_view(), name='delete_blog_post'),
    path('categories/', views.CategoryListView.as_view(), name='category_list'),
    path('categories/add_edit/', views.CategoryAddEditView.as_view(), name='add_edit_category'),
    path('categories/add_edit/<slug:category_slug>/', views.CategoryAddEditView.as_view(), name='add_edit_category'),
    path('categories/delete/<slug:category_slug>/', views.CategoryDeleteView.as_view(), name='delete_category'),
    path('order/<int:order_id>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('orders/', views.OrderListView.as_view(), name='order_list'),
    path('cart/list/', views.CartListView.as_view(), name='cart_list'),
    path('wishlist/list/', views.WishlistItemListView.as_view(), name='wishlist_item_list'),
    path('contacts/list/', views.ContactListView.as_view(), name='contact_list'),
    path('<path:not_found>', error_400_view, name='catch_all_404'),


]

handler400 = error_400_view

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('app2/', include('app2.urls')),

]

# To display images
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/app2/models.py
from django.db import models

# Create your models here.

ecommerce/app2/forms.py
from django import forms
from app.models import*
from django.contrib.auth.forms import  AuthenticationForm, UsernameField
from django.utils.translation import gettext, gettext_lazy as _



class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = '__all__'

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

class App2LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={'autofocus': True, 'class': 'form-control'}))
    password = forms.CharField(label=_("Password"), strip=False, widget=forms.PasswordInput(attrs={'autocomplete':'current-password', 'class':'form-control'}))

ecommerce/app2/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView
from django.urls import reverse_lazy
from app.models import*
from django.shortcuts import redirect, render, get_object_or_404 ,HttpResponseRedirect
from django.views import View
from .forms import*
from django.core.files import File
from django.db.models import Subquery, OuterRef
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .decorators import superadmin_required
from django.core.paginator import Paginator
from django.http import Http404
from django.db.models import Q
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import user_passes_test
from django.urls import reverse



def is_superuser(user):
    return user.is_authenticated and user.is_superuser


class App2LoginView(LoginView):
    template_name = 'app2/login.html'
    authentication_form = App2LoginForm 
    def form_invalid(self, form):
        if not self.request.user.is_superuser:
            url = reverse('app2:app2login')
            return HttpResponseRedirect(url + '?next=' + self.request.GET.get('next', '') + '&error=admin')
        
        return super().form_invalid(form)


@method_decorator([login_required(login_url='app2:app2login'), superadmin_required], name='dispatch')
class DashboardView(TemplateView):
    template_name = 'app2/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        return context

@method_decorator([login_required(login_url='app2:app2login'), superadmin_required], name='dispatch')
class ProductListView(View):
    def get(self, request):
        search_query = request.GET.get('q')
        sort_by = request.GET.get('sort_by', '-created_at')
        category_slug = request.GET.get('category')
        gender = request.GET.get('gender')
        page_number = request.GET.get('page', 1) 
       

        products = Product.objects.all()

        if search_query:
            products = products.filter(
                Q(title__icontains=search_query) |
                Q(category__title__icontains=search_query) |
                Q(short_description__icontains=search_query)
            )


        if gender:
            products = products.filter(gender=gender)

        if category_slug:
            category = get_object_or_404(Category, slug=category_slug)
            products = products.filter(category=category)

        products = products.order_by(sort_by)
        categories = Category.objects.all()
        paginator = Paginator(products, 10) 
        page = paginator.get_page(page_number)

        context = {'page':page,
                   'categories': categories,

                   }
        return render(request, 'app2/product_list.html', context)

@method_decorator([login_required(login_url='app2:app2login'), superadmin_required], name='dispatch')
class ProductAddEditView(View):
    def get(self, request,  product_slug=None):
        if product_slug:
            product = get_object_or_404(Product, slug=product_slug)
            form = ProductForm(instance=product)
        else:
            form = ProductForm()

        return render(request, 'app2/product_edit.html', {'form': form})

    def post(self, request, product_slug=None):
        if product_slug:
            product = get_object_or_404(Product, slug=product_slug)
            form = ProductForm(request.POST, request.FILES, instance=product)
        else:
            form = ProductForm(request.POST, request.FILES)

        if form.is_valid():
            instance = form.save(commit=False)

            new_image = form.cleaned_data.get('product_image')
            if new_image:
                instance.product_image.save(new_image.name, new_image, save=False)

            instance.save()

            return redirect('app2:product_list')

        return render(request, 'app2/product_edit.html', {'form': form})

@method_decorator([login_required(login_url='app2:app2login'), superadmin_required], name='dispatch')
class ProductDeleteView(View):
    def get(self, request, product_slug):
        product = get_object_or_404(Product, slug=product_slug)
        return render(request, 'app2/product_delete_confirm.html', {'product': product})

    def post(self, request, product_slug):
        product = get_object_or_404(Product, slug=product_slug)
        product.delete()
        return redirect('app2:product_list')
    
@method_decorator([login_required(login_url='app2:app2login'), superadmin_required], name='dispatch')
class BlogPostListView(View):
    def get(self, request):
        search_query = request.GET.get('q')
        sort_by = request.GET.get('sort_by', '-publish_date')
        page_number = request.GET.get('page', 1) 

        blog_posts = BlogPost.objects.all()

        if search_query:
            blog_posts = blog_posts.filter(
                Q(title__icontains=search_query) |
                Q(content__icontains=search_query)
            )

        blog_posts = blog_posts.order_by(sort_by)

        paginator = Paginator(blog_posts, 10) 
        page = paginator.get_page(page_number)

        return render(request, 'app2/blog_post_list.html', {'page': page})

@method_decorator([login_required(login_url='app2:app2login'), superadmin_required], name='dispatch')
class BlogPostAddEditView(View):
    def get(self, request, blog_post_slug=None):
        if blog_post_slug:
            blog_post = get_object_or_404(BlogPost, slug=blog_post_slug)
            form = BlogPostForm(instance=blog_post)
        else:
            form = BlogPostForm()

        return render(request, 'app2/blog_post_edit.html', {'form': form})

    def post(self, request, blog_post_slug=None):
        if blog_post_slug:
            blog_post = get_object_or_404(BlogPost, slug=blog_post_slug)
            form = BlogPostForm(request.POST, request.FILES, instance=blog_post)
        else:
            form = BlogPostForm(request.POST, request.FILES)

        if form.is_valid():
            instance = form.save()
            return redirect('app2:blog_post_list')

        return render(request, 'app2/blog_post_edit.html', {'form': form})
    
    
@method_decorator([login_required(login_url='app2:app2login'), superadmin_required], name='dispatch')
class BlogPostDeleteView(View):
    def get(self, request, blog_post_slug):  
        post = get_object_or_404(BlogPost, slug=blog_post_slug)
        return render(request, 'app2/blog_delete_confirm.html', {'post': post})

    def post(self, request, blog_post_slug):
        post = get_object_or_404(BlogPost, slug=blog_post_slug)
        post.delete()
        return redirect('app2:blog_post_list')


@method_decorator([login_required(login_url='app2:app2login'), superadmin_required], name='dispatch')
class CategoryListView(View):
    def get(self, request):
        # Get query parameters for search and sorting
        search_query = request.GET.get('q')
        sort_by = request.GET.get('sort_by', '-created_at')
        page_number = request.GET.get('page', 1)  # Default to page 1

        categories = Category.objects.all()

        if search_query:
            categories = categories.filter(
                Q(title__icontains=search_query) |
                Q(description__icontains=search_query)
            )

        categories = categories.order_by(sort_by)

        paginator = Paginator(categories, 10)  # 10 items per page
        page = paginator.get_page(page_number)

        return render(request, 'app2/category_list.html', {'page': page})

@method_decorator([login_required(login_url='app2:app2login'), superadmin_required], name='dispatch')
class CategoryAddEditView(View):
    def get(self, request, category_slug=None):
        if category_slug:
            category = get_object_or_404(Category, slug=category_slug)
            form = CategoryForm(instance=category)
        else:
            form = CategoryForm()

        return render(request, 'app2/category_edit.html', {'form': form})

    def post(self, request, category_slug=None):
        if category_slug:
            category = get_object_or_404(Category, slug=category_slug)
            form = CategoryForm(request.POST, request.FILES, instance=category)
        else:
            form = CategoryForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            return redirect('app2:category_list')

        return render(request, 'app2/category_edit.html', {'form': form})

@method_decorator([login_required(login_url='app2:app2login'), superadmin_required], name='dispatch')
class CategoryDeleteView(View):
    def get(self, request, category_slug):
        category = get_object_or_404(Category, slug=category_slug)
        return render(request, 'app2/category_delete_confirm.html', {'category': category})

    def post(self, request, category_slug):
        category = get_object_or_404(Category, slug=category_slug)
        category.delete()
        return redirect('app2:category_list')

@method_decorator([login_required(login_url='app2:app2login'), superadmin_required], name='dispatch')
class OrderDetailView(View):
    def get(self, request, order_id):
        order = get_object_or_404(Order, pk=order_id)
        return render(request, 'app2/order_detail.html', {'order': order})
    def post(self, request, order_id):
        order = get_object_or_404(Order, pk=order_id)
        new_status = request.POST.get('status')
        order.status = new_status
        order.save()
        return redirect('app2:order_list')

@method_decorator([login_required(login_url='app2:app2login'), superadmin_required], name='dispatch')
class OrderListView(View):
    def get(self, request):
        latest_orders = Order.objects.order_by('-ordered_date')
        

ecommerce/app2/templates/app2/blog_post_list.html
{% extends 'app2/base.html' %}
{% load static %}

{% block content %}
<div class="main_content_iner">
    <div class="container-fluid p-0 sm_padding_15px">
        <div class="add_button" style="text-align: right;">
            <a href="{% url 'app2:add_edit_blog_post' %}" class="btn btn-success btn-circle btn-lg">
                Add Blog <i class="fa fa-plus"></i>
            </a>
        </div>
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="row">
                    <div class="col-12">
                        <div class="serach_field-area">
                            <div class="search_inner">
                                <form method="get" action="{% url 'app2:blog_post_list' %}">
                                    <div class="search_field">
                                        <input type="text" name="q" value="{{ request.GET.q }}" placeholder="Search here...">
                                    </div>
                                    <button type="submit"> <img src="{% static 'app2/img/icon/icon_search.svg' %}" alt>
                                    </button>
                                </form>
                            </div>
                        </div>
                        <div class="sort_area">
                            <form method="get" action="{% url 'app2:blog_post_list' %}">
                                <div class="form-group">
                                    <label for="sort_by">Sort By:</label>
                                    <select name="sort_by" id="sort_by" onchange="this.form.submit()">
                                        <option value="-publish_date" {% if request.GET.sort_by == '-publish_date' %}selected{% endif %}>Newest</option>
                                        <option value="publish_date" {% if request.GET.sort_by == 'publish_date' %}selected{% endif %}>Oldest</option>
                                        <option value="title" {% if request.GET.sort_by == 'title' %}selected{% endif %}>Name(A-Z)</option>
                                        <option value="-title" {% if request.GET.sort_by == '-title' %}selected{% endif %}>Name(Z-A)</option>


                                    </select>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Blog Image</th>
                                        <th>Blog Title</th>
                                        <th>Content</th>
                                        <th>Edit</th>
                                        <th>Delete</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for blog_post in page %}
                                    <tr>
                                        <td><img src="{{ blog_post.image.url }}" alt="{{ blog_post.title }}" width="100"></td>
                                        <td>{{ blog_post.title }}</td>
                                        <td>{{ blog_post.content|striptags|truncatechars:100 }}</td>
                                        <td><a href="{% url 'app2:add_edit_blog_post' blog_post.slug %}" class="btn btn-primary">Edit</a></td>
                                        <td><a href="{% url 'app2:delete_blog_post' blog_post.slug %}" class="btn btn-danger">Delete</a></td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="pagination_area">
                            <nav aria-label="Page navigation example">
                                <ul class="pagination justify-content-center">
                                    {% if page.has_previous %}
                                    <li class="page-item"><a class="page-link" href="?page=1">&laquo;</a></li>
                                    <li class="page-item"><a class="page-link" href="?page={{ page.previous_page_number }}">{{ page.previous_page_number }}</a></li>
                                    {% endif %}
                                    <li class="page-item active"><a class="page-link" href="?page={{ page.number }}">{{ page.number }}</a></li>
                                    {% if page.has_next %}
                                    <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}">{{ page.next_page_number }}</a></li>
                                    <li class="page-item"><a class="page-link" href="?page={{ page.paginator.num_pages }}">&raquo;</a></li>
                                    {% endif %}
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

ecommerce/app2/templates/app2/category_list.html
{% extends 'app2/base.html' %}
{% load static %}

{% block content %}
<div class="main_content_iner">
    <div class="container-fluid p-0 sm_padding_15px">
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="row">
                    <div class="add_button" style="text-align: right;">
                        <a href="{% url 'app2:add_edit_category' %}" class="btn btn-success btn-circle btn-lg">
                            Add Category <i class="fa fa-plus"></i>
                        </a>
                    </div>
                    <div class="col-12">
                        <div class="serach_field-area">
                            <div class="search_inner">
                                <form method="get" action="{% url 'app2:category_list' %}">
                                    <div class="search_field">
                                        <input type="text" name="q" value="{{ request.GET.q }}" placeholder="Search here...">
                                    </div>
                                    <button type="submit"> <img src="{% static 'app2/img/icon/icon_search.svg' %}" alt>
                                    </button>
                                </form>
                            </div>
                        </div>
                        <div class="sort_area">
                            <form method="get" action="{% url 'app2:category_list' %}">
                                <div class="form-group">
                                    <label for="sort_by">Sort By:</label>
                                    <select name="sort_by" id="sort_by" onchange="this.form.submit()">
                                        <option value="-created_at" {% if request.GET.sort_by == '-created_at' %}selected{% endif %}>Newest</option>
                                        <option value="created_at" {% if request.GET.sort_by == 'created_at' %}selected{% endif %}>Oldest</option>
                                    </select>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Category Image</th>
                                        <th>Category Title</th>
                                        <th>Category Description</th>
                                        <th>Edit</th>
                                        <th>Delete</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for category in page %}
                                    <tr>
                                        <td><img src="{{ category.category_image.url }}" alt="{{ category.title }}" style="max-width: 100px; max-height:100px;" width="100"></td>
                                        <td>{{ category.title }}</td>
                                        <td>{{ category.description }}</td>
                                        <td><a href="{% url 'app2:add_edit_category' category.slug %}" class="btn btn-primary">Edit</a></td>
                                        <td><a href="{% url 'app2:delete_category' category.slug %}" class="btn btn-danger">Delete</a></td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="pagination_area">
                            <nav aria-label="Page navigation example">
                                <ul class="pagination justify-content-center">
                                    {% if page.has_previous %}
                                    <li class="page-item"><a class="page-link" href="?page=1">&laquo;</a></li>
                                    <li class="page-item"><a class="page-link" href="?page={{ page.previous_page_number }}">{{ page.previous_page_number }}</a></li>
                                    {% endif %}
                                    <li class="page-item active"><a class="page-link" href="?page={{ page.number }}">{{ page.number }}</a></li>
                                    {% if page.has_next %}
                                    <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}">{{ page.next_page_number }}</a></li>
                                    <li class="page-item"><a class="page-link" href="?page={{ page.paginator.num_pages }}">&raquo;</a></li>
                                    {% endif %}
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

ecommerce/app2/templates/app2/contact_list.html
{% extends 'app2/base.html' %}
{% load static %}

{% block content %}
<div class="main_content_iner">
    <div class="container-fluid p-0 sm_padding_15px">
        <div class="row justify-content-center">
            <div class="col-12">
                <h2>Contact List</h2>
                <div class="serach_field-area">
                    <div class="search_inner">
                        <form method="get" action="{% url 'app2:contact_list' %}">
                            <div class="search_field">
                                <input type="text" name="q" value="{{ request.GET.q }}" placeholder="Search here...">
                            </div>
                            <button type="submit"> <img src="{% static 'app2/img/icon/icon_search.svg' %}" alt>
                            </button>
                        </form>
                    </div>
                </div>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>First Name</th>
                                <th>Last Name</th>
                                <th>Email</th>
                                <th>Subject</th>
                                <th>Message</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for contact in page %}
                            <tr>
                                <td>{{ contact.firstname }}</td>
                                <td>{{ contact.lastname }}</td>
                                <td>{{ contact.email }}</td>
                                <td>{{ contact.subject }}</td>
                                <td>{{ contact.message }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="pagination_area">
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-center">
                            {% if page.has_previous %}
                            <li class="page-item"><a class="page-link" href="?page=1">&laquo;</a></li>
                            <li class="page-item"><a class="page-link" href="?page={{ page.previous_page_number }}">{{ page.previous_page_number }}</a></li>
                            {% endif %}
                            <li class="page-item active"><a class="page-link" href="?page={{ page.number }}">{{ page.number }}</a></li>
                            {% if page.has_next %}
                            <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}">{{ page.next_page_number }}</a></li>
                            <li class="page-item"><a class="page-link" href="?page={{ page.paginator.num_pages }}">&raquo;</a></li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}