ecommerce/app/urls.py
from .forms import LoginForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.urls import include, path
from . import views
from django.contrib.auth import views as auth_views
from .views import error_400_view
from rest_framework import routers
from .views import ProductViewSet

router = routers.DefaultRouter()
router.register(r'product', ProductViewSet)


app_name = 'app'


urlpatterns = [
    path('', views.home, name="home"),
       
    path('add-to-cart/', views.add_to_cart, name="add-to-cart"),
    path('remove-cart/<int:cart_id>/', views.remove_cart, name="remove-cart"),
    path('plus-cart/<int:cart_id>/', views.plus_cart, name="plus-cart"),
    path('minus-cart/<int:cart_id>/', views.minus_cart, name="minus-cart"),
    path('cart/', views.cart, name="cart"),
    path('checkout/', views.checkout, name="checkout"),
    path('orders/', views.orders, name="orders"),
    #URL for Products
    path('product/<slug:slug>/', views.detail, name="product-detail"),
    path('categories/', views.all_categories, name="all-categories"),
    path('shop/', views.shop, name="shop"),
    # URL for Authentication
    path('app/register/', views.RegistrationView.as_view(), name="register"),
    path('login/', auth_views.LoginView.as_view(template_name='app/login.html', authentication_form=LoginForm), name="login"),
    path('app/profile/', views.profile, name="profile"),
    path('app/add-address/', views.AddressView.as_view(), name="add-address"),
    path('app/remove-address/<int:id>/', views.remove_address, name="remove-address"),
    path('app/logout/', auth_views.LogoutView.as_view(next_page='app:login'), name="logout"),

    path('app/password-change/', auth_views.PasswordChangeView.as_view(template_name='app/password_change.html', form_class=PasswordChangeForm, success_url='/app/password-change-done/'), name="password-change"),
    path('password-change-done/', auth_views.PasswordChangeDoneView.as_view(template_name='app/password_change_done.html'), name="password-change-done"),

    path('app/password-reset/', auth_views.PasswordResetView.as_view(template_name='app/password_reset.html', form_class=PasswordResetForm, success_url='/app/password-reset/done/'), name="password-reset"), # Passing Success URL to Override default URL, also created password_reset_email.html due to error from our app_name in URL
    path('app/password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='app/password_reset_done.html'), name="password_reset_done"),
    path('app/password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='app/password_reset_confirm.html', form_class=SetPasswordForm, success_url='/app/password-reset-complete/'), name="password_reset_confirm"), # Passing Success URL to Override default URL
    path('app/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='app/password_reset_complete.html'), name="password_reset_complete"),

    path('product/test/', views.test, name="test"),
    path('add-to-wishlist/<int:prod_id>/', views.add_to_wishlist, name='add-to-wishlist'),
    path('shop/<slug:gender_slug>/category/<slug:category_slug>/', views.filter_by_gender_category, name='filter-by-gender-category'),
    path('blog/', views.blog, name='blog'),
    path('blog/<slug:slug>/', views.blog_detail, name='blog-detail'),
    path('contact', views.contact, name='contact'),
    path('wishlist/', views.wishlist, name='wishlist'),


    path('<slug:slug>/', views.category_products, name="category-products"),
    
    # path('<path:not_found>', error_400_view, name='catch_all_404'),

    
] 
# handler401 = error_400_view

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('app2/', include('app2.urls')),

]

# To display images
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/app/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor .fields import RichTextField
from django.utils.text import slugify
from decimal import Decimal





# Create your models here.
class Address(models.Model):
    user = models.ForeignKey(User, verbose_name="User", on_delete=models.CASCADE)
    locality = models.CharField(max_length=150, verbose_name="Nearest Location")
    city = models.CharField(max_length=150, verbose_name="City")
    state = models.CharField(max_length=150, verbose_name="State")

    def __str__(self):
        return self.locality


class Category(models.Model):
    title = models.CharField(max_length=50, verbose_name="Category Title")
    slug = models.SlugField(max_length=55, verbose_name="Category Slug")
    description = models.TextField(blank=True, verbose_name="Category Description")
    category_image = models.ImageField(upload_to='category', blank=True, null=True, verbose_name="Category Image")
    is_active = models.BooleanField()
    is_featured = models.BooleanField()
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Created Date")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Updated Date")

    class Meta:
        verbose_name_plural = 'Categories'
        ordering = ('-created_at', )

    def __str__(self):
        return self.title


class Product(models.Model):
    GENDER_CHOICES = (
        ('Men', 'Men'),
        ('Women', 'Women'),
        ('Unisex', 'Unisex'),
    )
    title = models.CharField(max_length=150, verbose_name="Product Title")
    slug = models.SlugField(max_length=160, verbose_name="Product Slug")
    sku = models.CharField(max_length=255, unique=True, verbose_name="Unique Product ID (SKU)")
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, default='Unisex')
    gender_slug = models.SlugField(max_length=10, editable=False)
    short_description = models.TextField(verbose_name="Short Description")
    detail_description = RichTextField()
    product_image = models.ImageField(upload_to='product',  null=True, verbose_name="Product Image")
    price = models.DecimalField(max_digits=8, decimal_places=2)
    category = models.ForeignKey(Category, verbose_name="Product Categoy", on_delete=models.DO_NOTHING)
    is_active = models.BooleanField()
    is_featured = models.BooleanField()
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Created Date")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Updated Date")

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created_at', )

    def __str__(self):
        return self.title
    def save(self, *args, **kwargs):
        self.gender_slug = slugify(self.gender)
        super().save(*args, **kwargs)


class Cart(models.Model):
    user = models.ForeignKey(User, verbose_name="User", on_delete=models.CASCADE)
    product = models.ForeignKey(Product, verbose_name="Product", on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1, verbose_name="Quantity")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Created Date")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Updated Date")

    def __str__(self):
        return str(self.user)
    
    # Creating Model Property to calculate Quantity x Price
    @property
    def total_price(self):
        return self.quantity * self.product.price

class WishlistItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Created Date")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Updated Date")
    def __str__(self):
        return f"{self.user.username}'s Wishlist: {self.product.title}"

STATUS_CHOICES = (
    ('Pending', 'Pending'),
    ('Accepted', 'Accepted'),
    ('Packed', 'Packed'),
    ('On The Way', 'On The Way'),
    ('Delivered', 'Delivered'),
    ('Cancelled', 'Cancelled')
)

class Order(models.Model):
    user = models.ForeignKey(User, verbose_name="User", on_delete=models.CASCADE)
    address = models.ForeignKey(Address, verbose_name="Shipping Address", on_delete=models.CASCADE)
    product = models.ForeignKey(Product, verbose_name="Product", on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name="Quantity")
    ordered_date = models.DateTimeField(auto_now_add=True, verbose_name="Ordered Date")
    price = models.DecimalField(max_digits=8, decimal_places=2)
    status = models.CharField(
        choices=STATUS_CHOICES,
        max_length=50,
        default="Pending"
        )
    def save(self, *args, **kwargs):
        self.price = Decimal(self.product.price) * self.quantity
        super(Order, self).save(*args, **kwargs)

class BlogPost(models.Model):
    title = models.CharField(max_length=200,verbose_name="Blog Post Title")
    slug = models.SlugField( max_length=55, verbose_name="Blog Post Slug", unique=True)
    content = RichTextField()
    image = models.ImageField(upload_to='blog', blank=True, null=True)
    publish_date = models.DateTimeField(auto_now=True)
    uploader = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.title
    
class Contacts(models.Model):
    firstname= models.CharField(max_length=150)
    lastname= models.CharField(max_length=150)
    email = models.EmailField()
    subject = models.CharField(max_length=200)
    message = models.TextField()

    class meta : 
        ordering = ['-id']

    def __str__(self):
        return self.firstname


class SocialMediaLink(models.Model):
    title = models.CharField(max_length=100)
    url = models.URLField()

    def __str__(self):
        return self.title
    
class HeroSection(models.Model):
    title = models.CharField(max_length=100)
    subtitle = models.CharField(max_length=200)
    image = models.ImageField()

    def __str__(self):
        return self.title
    
class ContactInfo(models.Model):
    address = models.CharField(max_length=255)
    city = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=20)
    email = models.EmailField()

    def __str__(self):
        return self.address

ecommerce/app/templates/app/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block metatitle %}watch Shop| Django Ecommerce{% endblock metatitle %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="{% static 'app/vendor/bootstrap/css/bootstrap.min.css' %}">
    <!-- Lightbox-->
    <link rel="stylesheet" href="{% static 'app/vendor/lightbox2/css/lightbox.min.css' %}">
    <!-- Range slider-->
    <link rel="stylesheet" href="{% static 'app/vendor/nouislider/nouislider.min.css' %}">
    <!-- Bootstrap select-->
    <link rel="stylesheet" href="{% static 'app/vendor/bootstrap-select/css/bootstrap-select.min.css' %}">
    <!-- Owl Carousel-->
    <link rel="stylesheet" href="{% static 'app/vendor/owl.carousel2/assets/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'app/vendor/owl.carousel2/assets/owl.theme.default.css' %}">
    <!-- Google fonts-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Libre+Franklin:wght@300;400;700&amp;display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Martel+Sans:wght@300;400;800&amp;display=swap">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC6Z5Sx6ZOz8AMwE93+cLvJYlW1O8EZ0MWU" crossorigin="anonymous">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'app/css/style.default.css' %}" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'app/css/custom.css' %}">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'app/img/favicon.png' %}">
    {% block css %}{% endblock %}
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
  </head>
  <body>
    <div class="page-holder">
      
      <!-- navbar-->
      <header class="header bg-white">
        <div class="container px-0 px-lg-3">
          <nav class="navbar navbar-expand-lg navbar-light py-3 px-lg-0"><a class="navbar-brand" href="{% url 'app:home' %}"><span class="font-weight-bold text-uppercase text-dark">Watch shop</span></a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <a class="nav-link active" href="{% url 'app:home' %}">Home</a>
                </li>
                <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" id="pagesDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories</a>
                  <div class="dropdown-menu mt-3" aria-labelledby="pagesDropdown">
                    {% if categories_menu %}
                      {% for cat_menu in categories_menu %}
                        <a class="dropdown-item border-0 transition-link" href="{% url 'app:shop' %}?category={{ cat_menu.slug }}">{{cat_menu.title}}</a>
                      {% endfor %}
                    {% endif %}
                    <hr>
                    <a class="dropdown-item border-0 transition-link" href="{% url 'app:all-categories' %}">All Categories</a>
                    
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'app:shop' %}">shop</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'app:blog' %}">Blog</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'app:contact' %}">Contact</a>
                </li>
              </ul>
              <ul class="navbar-nav ml-auto"> 
                {% if request.user.is_authenticated %}           
                  <li class="nav-item"><a class="nav-link" href="{% url 'app:cart' %}"> <i class="fas fa-dolly-flatbed mr-1 text-gray"></i>Cart<small class="text-gray">({{request.user.cart_set.count}})</small></a></li>
                  <li class="nav-item"><a class="nav-link" href="{%url 'app:wishlist'%}"> <i class="far fa-heart mr-1"></i><small class="text-gray"> ({{ wishlist_count }})</small></a></li>
                  {% comment %} <li class="nav-item"><a class="nav-link" href="#"> <i class="fas fa-user-alt mr-1 text-gray"></i>My Account</a></li> {% endcomment %}

                  <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" id="pagesDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user-alt mr-1 text-gray"></i>My Account</a></a>
                  
                  <div class="dropdown-menu mt-3" aria-labelledby="pagesDropdown">
                    
                      <a class="dropdown-item border-0 transition-link" href="{% url 'app:profile' %}">Profile</a>
                      <a class="dropdown-item border-0 transition-link" href="{% url 'app:cart' %}">Cart</a>
                      <a class="dropdown-item border-0 transition-link" href="{% url 'app:orders' %}">Orders</a>
                      <a class="dropdown-item border-0 transition-link" href="{% url 'app:password-change' %}">Change Password</a>

                    <hr>
                    <a class="dropdown-item border-0 transition-link" href="{% url 'app:logout' %}">Log Out</a>
                    
                </li>
                {% else %}
                  <li class="nav-item"><a class="nav-link" href="{% url 'app:login' %}">Login</a></li>
                  <li class="nav-item"><a class="nav-link" href="{% url 'app:register' %}">Create Account</a></li>
                {% endif %}   
              </ul>
            </div>
          </nav>
        </div>
      </header>


      {% block content %}

      {% endblock content %}

      
      <footer class="bg-dark text-white">
        <div class="container py-4">
          <div class="row py-5">
            <div class="col-md-4 mb-3 mb-md-0">
              <h6 class="text-uppercase mb-3">Customer services</h6>
              <ul class="list-unstyled mb-0">
                <li><a class="footer-link" href="{%url 'app:contact'%}">Help &amp; Contact Us</a></li>
                <li><a class="footer-link" href="{% url 'app:shop' %}">Shop</a></li>
              </ul>
            </div>
            <div class="col-md-4 mb-3 mb-md-0">
              <h6 class="text-uppercase mb-3">Company</h6>
              <ul class="list-unstyled mb-0">
                <li><a class="footer-link" href="{% url 'app:blog'%}">Blogs</a></li>
                <li><a class="footer-link" href="{%url 'app:contact'%}">contact</a></li>
              </ul>
            </div>
            <div class="col-md-4">
              <h6 class="text-uppercase mb-3">Social media</h6>
              <ul class="list-unstyled mb-0">
                {% for link in social_media_links %}
                <li><a class="footer-link" href="{{ link.url }}">{{ link.title }}</a></li>
                {% endfor %}
              </ul>
            </div>
          </div>
          <div class="border-top pt-4" style="border-color: #1d1d1d !important">
            <div class="row">
              <div class="col-lg-6">
                <p class="small text-muted mb-0">&copy; All rights reserved.</p>
              </div>
            </div>
          </div>
        </div>
      </footer>   
       {% include 'app/scripts.html' %}

ecommerce/app/templates/app/cart.html
{% extends 'app/base.html' %}
{% load static %}
{% load humanize %}

    {% block content %}
      <div class="container">
        <!-- HERO SECTION-->
        <section class="py-5 bg-light">
          <div class="container">
            <div class="row px-4 px-lg-5 py-lg-4 align-items-center">
              <div class="col-lg-6">
                <h1 class="h2 text-uppercase mb-0">Cart</h1>
              </div>
              <div class="col-lg-6 text-lg-right">
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb justify-content-lg-end mb-0 px-0">
                    <li class="breadcrumb-item"><a href="{% url 'app:home'%}">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Cart</li>
                  </ol>
                </nav>
              </div>
            </div>
          </div>
        </section>

        {% if cart_products %}
        <section class="py-5">
          <h2 class="h5 text-uppercase mb-4">Shopping cart</h2>

          {% include 'app/_messages.html' %}

          <div class="row">
            <div class="col-lg-8 mb-4 mb-lg-0">
              <!-- CART TABLE-->
              <div class="table-responsive mb-4">
                <table class="table">
                  <thead class="bg-light">
                    <tr>
                      <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Product</strong></th>
                      <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Price</strong></th>
                      <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Quantity</strong></th>
                      <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Total</strong></th>
                      <th class="border-0" scope="col"> </th>
                    </tr>
                  </thead>
                  <tbody>

                    {% for cart_product in cart_products %}
                    <tr>
                      <th class="pl-0 border-0" scope="row">
                        <div class="media align-items-center">

                          {% if cart_product.product.product_image %}
                            <a class="reset-anchor d-block animsition-link" href="{% url 'app:product-detail' cart_product.product.slug %}"><img src="{{cart_product.product.product_image.url}}" alt="{{cart_product.product.title}}" width="70"/></a>
                          {% else %}
                            <a class="reset-anchor d-block animsition-link" href="{% url 'app:product-detail' cart_product.product.slug %}"><img src="{% static 'app/img/product-detail-3.jpg' %}" alt="{{cart_product.product.title}}" width="70"/></a>
                          {% endif %}

                          <div class="media-body ml-3"><strong class="h6"><a class="reset-anchor animsition-link" href="{% url 'app:product-detail' cart_product.product.slug %}">{{cart_product.product.title}}</a></strong></div>
                        </div>
                      </th>
                      <td class="align-middle border-0">
                        <p class="mb-0 small">${{cart_product.product.price}}</p>
                      </td>
                      <td class="align-middle border-0">
                        <div class="border d-flex align-items-center justify-content-between px-3"><span class="small text-uppercase text-gray headings-font-family">Quantity</span>
                          <div class="quantity">
                            <a href="{% url 'app:minus-cart' cart_product.id %}" class="dec-btn p-0 ml-2"><i class="fas fa-minus"></i></a>
                            {% comment %} <button class="dec-btn p-0"><i class="fas fa-caret-left"></i></button> {% endcomment %}
                            <input class="form-control form-control-sm border-0 shadow-0 p-0" type="text" value="{{cart_product.quantity}}"/>
                            {% comment %} <button class="inc-btn p-0"><i class="fas fa-caret-right"></i></button> {% endcomment %}
                            <a href="{% url 'app:plus-cart' cart_product.id %}" class="inc-btn p-0"><i class="fas fa-plus"></i></a>
                          </div>
                        </div>
                      </td>
                      <td class="align-middle border-0">
                        <p class="mb-0 small">${{cart_product.total_price|intcomma}}</p>
                      </td>
                      <td class="align-middle border-0"><a class="reset-anchor" href="{% url 'app:remove-cart' cart_product.id %}"><i class="fas fa-trash-alt small text-muted"></i></a></td>
                    </tr>
                    {% endfor %}

                  </tbody>
                </table>
              </div>
              <!-- CART NAV-->
              <div class="bg-light px-4 py-3">
                <div class="row align-items-center text-center">
                  <div class="col-md-6 mb-3 mb-md-0 text-md-left"><a class="btn btn-link p-0 text-dark btn-sm" href="{% url 'app:home' %}"><i class="fas fa-long-arrow-alt-left mr-2"> </i>Continue shopping</a></div>
                  {% comment %} <div class="col-md-6 text-md-right"><a class="btn btn-outline-dark btn-sm" href="{% url 'app:checkout' %}">Procceed to checkout<i class="fas fa-long-arrow-alt-right ml-2"></i></a></div> {% endcomment %}
                </div>
              </div>
            </div>
            <!-- ORDER TOTAL-->
            <div class="col-lg-4">
              <div class="card border-0 rounded-0 p-lg-4 bg-light">
                <div class="card-body">
                  <h5 class="text-uppercase mb-4">Cart total</h5>
                  <ul class="list-unstyled mb-0">
                    <li class="d-flex align-items-center justify-content-between"><strong class="text-uppercase small font-weight-bold">Subtotal</strong><span class="text-muted small">${{amount|intcomma}}</span></li>
                    <li class="d-flex align-items-center justify-content-between"><strong class="text-uppercase small font-weight-bold">Shipping Charge</strong><span class="text-muted small">+ ${{shipping_amount}}</span></li>
                    <li class="border-bottom my-2"></li>
                    <li class="d-flex align-items-center justify-content-between mb-4"><strong class="text-uppercase small font-weight-bold">Total</strong><span>${{total_amount|intcomma}}</span></li>
                    <li>

                      {% comment %} <form action="#">
                        <div class="form-group mb-0">
                          <input class="form-control" type="text" placeholder="Enter your coupon">
                          <button class="btn btn-dark btn-sm btn-block" type="submit"> <i class="fas fa-gift mr-2"></i>Apply coupon</button>
                        </div>
                      </form> {% endcomment %}

                    </li>
                  </ul>

                  
                  <h5 class="text-uppercase my-5">Select Shipping Address</h5>
                  
                  <form action="{% url 'app:checkout' %}" id="myform">

                    {% if addresses %}
                      {% for address in addresses %}
                        <div class="mb-3">
                        <input type="radio" name="address" value="{{address.id}}"> <strong>Address {{forloop.counter}}</strong> <br>
                        ( {{address.locality}}, {{address.city}}, {{address.state}} )
                        </div>
                      {% endfor %}
                    {% endif %}
                    <p><a class="btn btn-primary btn-large" href="{% url 'app:add-address'%}">Add new Address »</a> </p>
                    <!-- Set up a container element for the button -->
                    {% comment %} <div class="text-end" id="paypal-button-container"></div> {% endcomment %}

                    {% comment %} For Cash on Delivery {% endcomment %}
                    <button type="submit" class="btn btn-dark btn-lg btn-outline-dark" type="submit"> <i class="fas fa-dollar-sign mr-2"></i>Cash on Delivery</button>

                  </form>

                </div>
              </div>
            </div>

          </div>
        </section>
        
        {% else %}

          <div class="text-center py-5">
            <h3 class="mb-3">Your cart is empty.</h3>
            <a href="{% url 'app:home' %}"><i class="fas fa-long-arrow-alt-left mr-2"> </i>Continue shopping</a>
          </div>

        {% endif %}

      </div>
      {% endblock content %}

ecommerce/app/templates/app/wishlist.html
{% extends 'app/base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
<div class="container">
    <!-- HERO SECTION -->
    <section class="py-5 bg-light">
        <div class="container">
            <div class="row px-4 px-lg-5 py-lg-4 align-items-center">
                <div class="col-lg-6">
                    <h1 class="h2 text-uppercase mb-0">Cart</h1>
                </div>
                <div class="col-lg-6 text-lg-right">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-lg-end mb-0 px-0">
                            <li class="breadcrumb-item"><a href="{% url 'app:home' %}">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Wishlist</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </section>
    <div class="row">
        <div class="col-lg-12">
            <div class="cart-table">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th scope="col">Product</th>
                            <th scope="col">Price</th>
                            <th scope="col">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                      {% for item in wishlist_items %}
                      <tr>
                          <td class="product-thumbnail">
                              <a href="{% url 'app:product-detail' slug=item.product.slug %}">
                                  <img src="{{ item.product.product_image.url }}" style="height: 80px; width: 80px;" alt="{{ item.product.title }}">
                              </a>
                          </td>
                          <td class="product-price">{{ item.product.price|floatformat:2 }}</td>
                          <td class="product-actions">
                            <div class="d-flex">
                                <div class="mr-2">
                                    <form action="{% url 'app:add-to-cart' %}">
                                        <input type="hidden" name="prod_id" value="{{ item.product.id }}" id="product_id">
                                        {% if item.product.id in cart_product_ids %}
                                            <button type="submit" class="btn btn-sm btn-primary">Remove from Cart</button>
                                        {% else %}
                                            <button type="submit" class="btn btn-sm btn-primary">Add to Cart</button>
                                        {% endif %}
                                    </form>
                                </div>
                                <div>
                                    <form method="post" action="{% url 'app:add-to-wishlist' item.product.id %}">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-danger btn-sm">Remove</button>
                                    </form>
                                </div>
                            </div>
                        </td>
                        
                      </tr>
                      {% endfor %}
                  </tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock content %}